/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.91
 * Generated at: 2023-10-19 21:07:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.domain.Product;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.domain.Product");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>4Log Products - Admin Panel</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" href=\"./CSS/global.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"./CSS/index.css\"/>\n");
      out.write("        \n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"https://cdn-icons-png.flaticon.com/512/6947/6947559.png\"/>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <h1>4LOG Products.</h1>\n");
      out.write("               \n");
      out.write("            <main>\n");
      out.write("                <form name=\"new-product\" method=\"POST\" action=\"/website/products\">\n");
      out.write("                    <h2>Save a product</h2>\n");
      out.write("\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"name-input\">Name</label>\n");
      out.write("                        <input type=\"text\" name=\"name-input\" id=\"name-input\" placeholder=\"Insert a product name\" minlength=\"1\" maxlength=\"50\" required=\"true\"/>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"brand-input\">Brand</label>\n");
      out.write("                        <input type=\"text\" name=\"brand-input\" id=\"brand-input\" placeholder=\"Insert a product name\" minlength=\"1\" maxlength=\"50\" required=\"true\"/>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div>\n");
      out.write("                        <label for=\"price-input\">Price</label>\n");
      out.write("                        <input type=\"number\" min=\"1\" step=\"any\" name=\"price-input\" id=\"price-input\" placeholder=\"Insert a product price\" required=\"true\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <input type=\"submit\" value=\"Add\" name=\"submit-btn\" />\n");
      out.write("                </form>\n");
      out.write("                \n");
      out.write("                <form name=\"find-all\" id=\"findAllTB\" method=\"GET\" action=\"/website/products\">\n");
      out.write("                            ");

                                List<Product> productList = (List<Product>) request.getAttribute("products");
                            
                                if(productList == null) {
                            
      out.write("\n");
      out.write("                                <div>\n");
      out.write("                                    <button type=\"submit\">Fill table...</button>\n");
      out.write("                                </div>\n");
      out.write("                                \n");
      out.write("                                <p>Fill table to see all products...</p>\n");
      out.write("                            ");

                                } else {
                            
      out.write("\n");
      out.write("                                <div>\n");
      out.write("                                    <button type=\"submit\">Update table...</button>\n");
      out.write("                                </div>\n");
      out.write("                                <table border=\"1\">\n");
      out.write("                                    <thead>\n");
      out.write("                                        <tr>\n");
      out.write("                                            <th>Name</th>\n");
      out.write("                                            <th>Brand</th>\n");
      out.write("                                            <th>Price</th>\n");
      out.write("                                            <th>Created At</th>\n");
      out.write("                                        </tr>\n");
      out.write("                                    </thead>\n");
      out.write("                                    <tbody>\n");
      out.write("                            ");

                                    for(Product product : productList) {
                            
      out.write("\n");
      out.write("                                        <tr>\n");
      out.write("                                            <td>");
      out.print( product.getLgName() );
      out.write("</td>\n");
      out.write("                                            <td>");
      out.print( product.getLgBrand() );
      out.write("</td>\n");
      out.write("                                            <td>$ ");
      out.print( product.getLgPrice() );
      out.write("</td>\n");
      out.write("                                            <td>");
      out.print( product.getLgcreatedAt() );
      out.write("</td>\n");
      out.write("                                        </tr>\n");
      out.write("                            ");

                                    }
                            
      out.write("\n");
      out.write("                                    </tbody>\n");
      out.write("                                </table>\n");
      out.write("                            ");

                                }
                            
      out.write("\n");
      out.write("                </form>\n");
      out.write("            </main>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"footer\">\n");
      out.write("            <p>Development by <a href=\"github.com/Matheus-FSantos\" target=\"_blank\">Matheus Ferreira Santos</a>.</p>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
