/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.91
 * Generated at: 2023-09-15 13:32:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"pt-BR\">\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("        \n");
      out.write("        <link rel=\"stylesheet\" href=\"CSS/global.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"CSS/home/index.css\"/>\n");
      out.write("\n");
      out.write("        <!-- Animated CSS -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css\"/>\n");
      out.write("        \n");
      out.write("        <!-- Font Awesome -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\"/>\n");
      out.write("        \n");
      out.write("        <title>Home</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"viewContent animate__animated animate__fadeIn\">\n");
      out.write("            <header class=\"c-header\">\n");
      out.write("                <h1 class=\"c-h-title\">2-Log</h1>\n");
      out.write("                <form action=\"user\" method=\"post\">\n");
      out.write("                    <input type=\"hidden\" name=\"flag\" value=\"login\"/>\n");
      out.write("                    <div class=\"form-container\">\n");
      out.write("                        <div class=\"form-field\">\n");
      out.write("                            <label class=\"label gap-10\">E-mail</label>\n");
      out.write("                            <input class=\"input\" type=\"email\" name=\"username\" placeholder=\"Ex.: ex@ex.com\" required=\"true\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"form-field\">\n");
      out.write("                            <label class=\"label gap-10\">Senha</label>\n");
      out.write("                            <input class=\"input\" type=\"password\" name=\"password\" placeholder=\"Ex.: 1234\" required=\"true\">\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <input class=\"btn align-center\" type=\"submit\" value=\"Login\"/>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </header>\n");
      out.write("            \n");
      out.write("            <nav class=\"c-nav\">\n");
      out.write("                \n");
      out.write("            </nav>\n");
      out.write("            <main class=\"c-main\">\n");
      out.write("                <iframe src=\"./JSPs/inicial.jsp\" name=\"centro\" class=\"iframe-container\"></iframe>\n");
      out.write("            </main>\n");
      out.write("            <footer class=\"c-footer\">\n");
      out.write("                <div class=\"c-f-content\">\n");
      out.write("                    <a class=\"c-f-c-title\" href=\"https://github.com/Matheus-FSantos\" target=\"_blank\">Matheus Ferreira Santos</a>\n");
      out.write("                    <p class=\"c-f-c-logo\">2-Log</p>\n");
      out.write("                    <p class=\"c-f-c-date\">Agosto de 2023</p>\n");
      out.write("                </div>\n");
      out.write("            </footer>\n");
      out.write("            \n");
      out.write("            <div class=\"pricing-btn animate__animated animate__rotateInDownRight\">\n");
      out.write("                <figure>\n");
      out.write("                    <i class=\"fa-solid fa-plus padding-left-5 fa-xl btn-more-icon animate__animated animate__fadeIn\">&nbsp;</i>\n");
      out.write("                </figure>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"careers-btn animate__animated animate__rotateInDownRight\">\n");
      out.write("                <figure>\n");
      out.write("                    <i class=\"fa-solid fa-address-book padding-left-5 fa-xl btn-more-icon animate__animated animate__fadeIn\">&nbsp;</i>\n");
      out.write("                </figure>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"contact-btn animate__animated animate__rotateInDownRight\">\n");
      out.write("                <figure>\n");
      out.write("                    <i class=\"fa-solid fa-trash fa-xl padding-left-2 btn-more-icon animate__animated animate__fadeIn\">&nbsp;</i>\n");
      out.write("                </figure>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
