/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.91
 * Generated at: 2023-10-20 12:09:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.domain.Funcionario;
import java.util.List;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("model.domain.Funcionario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h1>Product List</h1>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <!-- Formulário de cadastro de produto -->\n");
      out.write("        <form name=\"save-a-product\" method=\"POST\" action=\"/WebApplication1/funcionarios\">\n");
      out.write("            <label for=\"nome-input\">Nome</label>\n");
      out.write("            <input id=\"nome-input\" name=\"nome-input\" placeholder=\"Insira o nome\" minlength=\"1\" minlength=\"80\" required=\"true\"/>\n");
      out.write("            <br/>\n");
      out.write("            \n");
      out.write("            <label for=\"endereco-input\">Endereco</label>\n");
      out.write("            <input id=\"endereco-input\" name=\"endereco-input\" placeholder=\"Insira o endereco\" minlength=\"1\" minlength=\"70\" required=\"true\"/>\n");
      out.write("            <br/>\n");
      out.write("            \n");
      out.write("            <label for=\"bairro-input\">Bairro</label>\n");
      out.write("            <input id=\"bairro-input\" name=\"bairro-input\" placeholder=\"Insira o bairro\" minlength=\"1\" minlength=\"50\" required=\"true\"/>\n");
      out.write("            <br/>\n");
      out.write("            \n");
      out.write("            <label for=\"cidade-input\">Cidade</label>\n");
      out.write("            <input id=\"cidade-input\" name=\"cidade-input\" placeholder=\"Insira a cidade\" minlength=\"1\" minlength=\"40\" required=\"true\"/>\n");
      out.write("            <br/>\n");
      out.write("            \n");
      out.write("            <label for=\"cargo-input\">Cargo</label>\n");
      out.write("            <input id=\"cargo-input\" name=\"cargo-input\" placeholder=\"Insira o cargo\" minlength=\"1\" minlength=\"40\" required=\"true\"/>\n");
      out.write("            <br/>\n");
      out.write("            \n");
      out.write("            <label for=\"salario-input\">Salario</label>\n");
      out.write("            <input type=\"number\" min=\"1\" step=\"any\" id=\"salario-input\" name=\"salario-input\" placeholder=\"Insira o salario\" required=\"true\"/>\n");
      out.write("            <br/>\n");
      out.write("            \n");
      out.write("            <input type=\"submit\" value=\"Submit\" />\n");
      out.write("        </form>\n");
      out.write("        \n");
      out.write("        <!-- Tabela de listagem de produtos -->\n");
      out.write("        ");

            List<Funcionario> funcionarioList = (List<Funcionario>) request.getAttribute("funcionarios");
            
            if(funcionarioList == null) {
        
      out.write("\n");
      out.write("                <p>Fill table to see all employees.</p>\n");
      out.write("                <form name=\"find-all\" action=\"/WebApplication1/funcionarios\">\n");
      out.write("                    <input type=\"submit\" value=\"Fill table\" />\n");
      out.write("                </form>\n");
      out.write("        ");

            } else {
        
      out.write("\n");
      out.write("                <form name=\"find-all\" method=\"GET\" action=\"/WebApplication1/funcionarios\">\n");
      out.write("                    <input type=\"submit\" value=\"Update table\" />\n");
      out.write("                </form>\n");
      out.write("                <table border=\"1\">\n");
      out.write("                <thead>\n");
      out.write("                    <tr>\n");
      out.write("                        <th>Nome</th>\n");
      out.write("                        <th>Endereco</th>\n");
      out.write("                        <th>Bairro</th>\n");
      out.write("                        <th>Cidade</th>\n");
      out.write("                        <th>Cargo</th>\n");
      out.write("                        <th>Salario</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("        ");
  
                for(Funcionario funcionario : funcionarioList) {  
        
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>");
      out.print( funcionario.getFNome());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( funcionario.getFEndereco());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( funcionario.getFBairro());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( funcionario.getFCidade());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( funcionario.getFCargo());
      out.write("</td>\n");
      out.write("                        <td>$ ");
      out.print( funcionario.getFSalario());
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("        ");
    
                }
        
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("        ");

            }
        
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
